version: "2"

services:
  crawler:
    container_name: crawler
    image: golang:1.8
    volumes:
      - .:/go/src/github.com/maddevsio/spiderwoman/
    working_dir: /go/src/github.com/maddevsio/spiderwoman/
    environment:
      - DB-PATH=/res.db
    command: make run-once
  api:
    container_name: api
    image: golang:1.8
    volumes:
      - .:/go/src/github.com/maddevsio/spiderwoman/
      - ./api/:/go/src/github.com/maddevsio/spiderwoman/api/
    working_dir: /go/src/github.com/maddevsio/spiderwoman/api/
    environment:
      - DB-PATH=/res.db
    depends_on:
      - crawler
    ports:
      - "8080:8080"
    command: go run main.go
