version: "2"

services:
  app:
    image: golang:1.8
    volumes:
      - .:/go/src/github.com/maddevsio/spiderwoman
    working_dir: /go/src/github.com/maddevsio/spiderwoman
    command: make run-forever
