version: "2"

services:
  spiderdb:
    container_name: spiderdb
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./database:/docker-entrypoint-initdb.d
  crawler:
    container_name: crawler
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /go/src/github.com/maddevsio/spiderwoman/
    depends_on:
      - spiderdb
    command: ["./wait-for-mysql.sh", "spiderdb", "30", "make run-forever"]
  api:
    container_name: api
    build:
      context: .
      dockerfile: ./api/Dockerfile
    working_dir: /go/src/github.com/maddevsio/spiderwoman/api/
    depends_on:
      - crawler
    ports:
      - "8080:8080"
    command: go run ./main.go
