version: "2"

services:

  mysql:
    image: mysql:5.7
    environment:
     - MYSQL_ALLOW_EMPTY_PASSWORD=true
    volumes:
      - /usr/local/opt/docker-volumes/mysql-spiderwoman:/var/lib/mysql:rw
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    ports:
     - 127.0.0.1:3306:3306

  pma:
    ports:
     - 8090:80
    links:
     - mysql:db
    image: phpmyadmin/phpmyadmin

  crawler:
    container_name: crawler
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /go/src/github.com/maddevsio/spiderwoman/
    depends_on:
      - mysql
    command: make run-once
    #command: ["./wait-for-mysql.sh", "mysql", "30", "make run-once"]

  api:
    container_name: api
    build:
      context: .
      dockerfile: ./api/Dockerfile
    working_dir: /go/src/github.com/maddevsio/spiderwoman/api/
    depends_on:
      - mysql
    ports:
      - 8080:8080
    command: make run